# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 112Webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_5eb4ec6054f240aca052bdb7472b4ff6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3794db817f6148b39baba93752c9744a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5eb4ec6054f240aca052bdb7472b4ff6 }}/mcr.microsoft.com/azuredocs/aci-helloworld:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '112Webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a6097de7e54348ecb58a92da6ab9aea7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5eb4ec6054f240aca052bdb7472b4ff6 }}/mcr.microsoft.com/azuredocs/aci-helloworld:${{ github.sha }}'